# Generated by Django 5.0.4 on 2024-04-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_company_technologies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="technologies",
        ),
        migrations.AddField(
            model_name="tech",
            name="companies_using",
            field=models.ManyToManyField(related_name="technologies", to="app.company"),
        ),
    ]
