# Generated by Django 5.0.4 on 2024-04-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=45)),
                ("tech", models.CharField(max_length=45)),
                ("category", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Tech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("category", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=45)),
                ("url", models.TextField(default="Null")),
                ("logourl", models.TextField(default="Null")),
                (
                    "technologies",
                    models.ManyToManyField(
                        related_name="companies_using", to="app.tech"
                    ),
                ),
            ],
        ),
    ]
